import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import About from "@/components/shared/About";
import Skills from "@/components/shared/Skills";
import MyProject from "@/components/shared/MyProject";
import MyExperience from "@/components/shared/MyExperience";
import MyContact from "@/components/shared/MyContact";
import Footer from "@/components/shared/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <Navbar></Navbar>
        {children}
        <About></About>
        <Skills></Skills>
         <MyProject></MyProject>
          <MyExperience></MyExperience>
          <MyContact></MyContact>
          <Footer></Footer>
        </body>
    </html>
  );
}
